# Generated by Django 5.0.2 on 2024-03-19 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phone_Number', models.IntegerField()),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=255)),
                ('Weight', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phone_Number', models.IntegerField()),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('Doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyHMSApp.doctors')),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyHMSApp.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine', models.CharField(max_length=255)),
                ('Date_created', models.DateField()),
                ('Doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyHMSApp.doctors')),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyHMSApp.patients')),
            ],
        ),
    ]
