# Generated by Django 5.0.2 on 2024-03-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyHMSApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Doctor_id',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Patient_id',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='prescriptions',
            old_name='Doctor_id',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='prescriptions',
            old_name='Patient_id',
            new_name='Patient',
        ),
    ]
