# Generated by Django 5.0.2 on 2024-03-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHMSApp', '0002_rename_doctor_id_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
