# Generated by Django 5.0.2 on 2024-03-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHMSApp', '0003_alter_doctors_email_alter_patients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Phone_Number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Phone_Number',
            field=models.BigIntegerField(),
        ),
    ]
