# Generated by Django 5.0.2 on 2024-03-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHMSApp', '0004_alter_doctors_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='Date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
